name: Build Jar

inputs:
  github_token:
    description: 'Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}'
    required: true
  repository:
    description: 'Repository name to push. Default or empty value represents current github repository (${GITHUB_REPOSITORY})'
    default: ''
    required: false
  branch:
    description: 'Destination branch to push changes'
    required: false
    default: 'master'
  force:
    description: 'Determines if force push is used'
    required: false
  directory:
    description: 'Directory to change to before pushing.'
    required: false
    default: '.'

on:
  push:
    paths-ignore:
      - '*.jar'
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.7
      uses: actions/setup-java@v1
      with:
        java-version: 1.7
    - name: Build
      run: cd src/build/; ./build.sh
    - name: Run
      run: java -jar src/build/acp_commander.jar  
    - name: copy
      run: cp src/build/acp_commander.jar .
    - name: set git user name
      run: git config user.name "workflow@github" 
    - name: set git user email
      run: git config user.email "workflow@github" 
    - name: commit
      run: git commit -m "generate jar from latest source" acp_commander.jar
    - name: push
      run: git push https://${GITHUB_ACTOR}:${INPUT_GITHUB_TOKEN}@github.com/${REPOSITORY}.git HEAD:master
