name: Build Jar

on: [push]
  branches:
    - development

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.6
      uses: actions/setup-java@v1
      with:
        java-version: 1.6
    - name: Build
      run: cd src/build/; ./build.sh
    - name: Run
      run: java -jar src/build/acp_commander.jar  
