name: Build Jar

on:
  push:
    paths-ignore:
      - '*.jar'
        
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.7
      uses: actions/setup-java@v1
      with:
        java-version: 1.7
    - name: Build
      run: cd src/build/; ./build.sh
    - name: Run
      run: java -jar src/build/acp_commander.jar  
    - name: copy
      run: cp src/build/acp_commander.jar .
    - name: commit
      run: git commit -m "generate jar from latest source" acp_commander.jar
