name: Build Jar

on:
  push:
    paths-ignore:
      - '*.jar'
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.7
      uses: actions/setup-java@v1
      with:
        java-version: 1.7
        github-token: "${{ secrets.GITHUB_TOKEN }}"
    - name: Build
      run: cd src/build/; ./build.sh
    - name: Run
      run: java -jar src/build/acp_commander.jar  
    - name: copy
      run: cp src/build/acp_commander.jar .
    - name: set git user name
      run: git config user.name "workflow@github" 
    - name: set git user email
      run: git config user.email "workflow@github" 
    - name: commit
      run: git commit -m "generate jar from latest source" acp_commander.jar
    - name: push
      run: git push https://${{github.actor}}:{{github-token}}@github.com/${{github.GITHUB_REPOSITORY}}.git HEAD:master
