on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: launch test target
    steps:
    - name: test
      id: hello
      uses: 1000001101000/acp-commander/acptest@master
      env:
        key1: ${{secrets.KEY1}} 
